[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
lib_deps =
  miguelbalboa/MFRC522
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  olkal/HX711_ADC
